### PR TITLE
Logging flags

### LINKED ISSUE #311: Console output appearing in build service server logs
Particularly this:

https://github.com/Financial-Times/origami-build-tools/blob/master/lib/tasks/build.js#L61

Since I'm trying to update the build service logging, this unformatted log line is getting in the way. Is it possible to silence OBT's logging to console, and have it throw exceptions if it's unhappy?

### PR DESCRIPTION
**Pull request by AlbertoElias**
Closes #311

### CODE REVIEW

File: lib/helpers/log.js [hunk 1]
```diff
@@ -2,32 +2,35 @@
...
-var debugLog = function() {};
+const noOp = () => {};
 
-if (process.env.OBT_DEBUG === 'true') {
-	debugLog = function(text) {
-		console.log(String(text).grey);
-	};
-}
+const logLevelNormal = process.env.OBT_LOG_LEVEL !== 'none';
+const logLevelDebug = process.env.OBT_LOG_LEVEL === 'debug';
```
Comment (triblondon) [inline lib/helpers/log.js]: I was a tad confused by this naming, maybe use `minLogLevel`.  The current names initially sound like constants for bitwise flags.  Not a big thing.

**Comment by AlbertoElias** [comment]
@triblondon I changed the names
